### ISSUE TITLE
How to add contributions?

### ISSUE THREAD

**Issue by Bovine-collab** [Open-CSP/PageSync-SharedFiles#1]
I'd like to contribute an addition to the following templates:

- Parameter definition
- Generate sidebar template code

So they support localisation labels (`{{int:label}}`).

Is there a way to do this directly in Git, or does it have to be through a Zip file?

I've added the pages below.

[Page contributions.zip](https://github.com/Open-CSP/PageSync-SharedFiles/files/10995106/Page.contributions.zip)

**Comment by Designburo** [comment]
Hi!

To create a share file, you use the Share file option from the Special Page. Documentation can be found here :
https://www.open-csp.org/DevOps:Doc/PageSync/2.1/share_pages

Currently adding files to the shared repo is very basic and the docs can be found here : https://www.open-csp.org/DevOps:Doc/PageSync/2.1/submit_a_share_file

**Comment by Bovine-collab** [comment]
Thanks for the quick help! I’ll try that as soon as I get a chance.
